name: Release plugin

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  PLUGIN_NAME: cloudflare-ai
  NODE_VERSION: 22
  PNPM_VERSION: 8

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for getting tags

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Install dependencies and build
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Prepare release assets
        id: prepare_assets
        run: |
          mkdir ${{ env.PLUGIN_NAME }}
          cp build/{main.js,manifest.json,styles.css} ${{ env.PLUGIN_NAME }}/
          zip -r ${{ env.PLUGIN_NAME }}-${{ steps.get_version.outputs.VERSION }}.zip ${{ env.PLUGIN_NAME }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.PLUGIN_NAME }}-${{ steps.get_version.outputs.VERSION }}.zip
            build/main.js
            build/manifest.json
            build/styles.css
            build/versions.json
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}